### ISSUE TITLE
How to use with GBDK 2020 on linux?

### ISSUE THREAD

**Issue by irishgreencitrus** [SuperDisk/hUGEDriver#11]
I can't seem to find any information about how to use the gbdk example on linux. if there's a way please add it to the README! thanks

**Comment by basxto** [comment]
```
git clone https://github.com/SuperDisk/hUGEDriver.git
cd  hUGEDriver/gbdk_example/
make -C ../tools
cat build.bat | sed "s/::/#/g" | sed "s|rgb2sdas|../tools/rgb2sdas|g" > build.sh
chmod +x build.sh
./build.sh
```

**Comment by SuperDisk** [comment]
@irishgreencitrus sorry for not answering quickly, but does the above comment address your issue?

**Comment by odrevet** [comment]
I am trying to build using @basxto 's answer. 
For the record: 
Free pascal is needed to build (`sudo apt install fpc`)
rgbasm is from [rgbds](https://github.com/gbdev/rgbds) 

Linux binaries could be pre-build and put into release (along with windows provided exe) like GBDK does

**Comment by SuperDisk** [comment]
Hi, check out the GitHub actions for pre-built Linux versions. Be sure to install rgbds using apt first.

https://github.com/SuperDisk/hUGETracker/actions/runs/3325654451

**Comment by odrevet** [comment]
Thank you very much, 
I think you wanted to link to https://github.com/SuperDisk/hUGEDriver/actions 
I also needed  the hUGETracker linux bin anyway :)
