### ISSUE TITLE
Support for RGB9, revision 8

### ISSUE THREAD

**Issue by irishgreencitrus** [SuperDisk/hUGEDriver#12]
ERROR: Unsupported object file version! This version of rgb2sdas supports RGB9, revision 6 & 7 files. The provided file is RGB9, revision 8.

**Comment by SuperDisk** [comment]
Oh, looks like you got rgb2sdas working! Seems like the RGBDS folks put out another new file version that we need to support-- I'll update ASAP.

**Comment by irishgreencitrus** [comment]
> Oh, looks like you got rgb2sdas working! Seems like the RGBDS folks put out another new file version that we need to support-- I'll update ASAP.

Realised you need a pascal compiler but it'd be nice to have some binaries for linux too. If you want to close that issue you can, but please put a note about compiling in the README at least, it would of saved me around a half hour of research!

**Comment by ISSOtm** [comment]
Worth adding CI for `rgb2sdas`?

**Comment by SuperDisk** [comment]
@ISSOtm Yep, I'll look into it. I updated rgb2sdas though so this particular issue can be closed.
