### ISSUE TITLE
Support a music bank

### ISSUE THREAD

**Issue by basxto** [SuperDisk/hUGEDriver#24]
Carillon Player allows to run from a special bank with a fixed jump table that can be used to call it:
* `Player_Initialize` at `$4000`
* `Player_MusicStart` at `$4003`
* `Player_MusicStop` at `$4006`
* `Player_SongSelect` at `$400c`
* `Player_MusicUpdate` at `$4100`

Being compatible with that would have two benefits:
* Roms that use Carillon Player could easily switch to hUGEDriver
* It could become an alternative solution for combining it with C functions without the need to translate the assembly

**Comment by SuperDisk** [comment]
What's the benefit of having a fixed set of addresses to call? I'm not sure what you mean by the two bullet points.

**Comment by basxto** [comment]
You can update and build the player separately, these addresses just have jumps to the real functions.

The point of the second bullet point is this:
The hUGEDriver bank could be built with rgbds and later concatenated to the rom.
sdasgb, asgb and other assemblers only need to know the bank number and the addresses within the bank to interface with the driver.
If the tracks are also placed at a predefined position, that would even allow to supply a prebuilt player and just patch in the music. Or to update the player without touching the music and the rest of the rom.

**Comment by SuperDisk** [comment]
But why would you want to do that? You can convert hUGEDriver to `sdas`'s native format with `rgb2sdas` and then not have to deal with concatenation or anything.

**Comment by basxto** [comment]
It does not work with SDCC 4.2.0
```
?ASlink-Warning-Conflicting sdcc options:
   "-mgbz80" in module "hUGEDriver_obj" and
   "-msm83" in module "sdcc_player_example".
?ASlink-Warning-Conflicting sdcc options:
   "-mgbz80" in module "hUGEDriver_obj" and
   "-msm83" in module "sample_song".
```

**Comment by SuperDisk** [comment]
Yeah, it looks like SDCC has renamed gbz80 to sm83. I ran into this exact issue actually while compiling the GBDK toolchain the other day. The current release of GBDK doesn't support SDCC 4.2.0, so I'll update the tool once it switches over.

**Comment by basxto** [comment]
I’m writing wrappers for the new calling convention and an example for pure SDCC (no interaction, display, interrupts, just music).
It looks like you can just drop the `O` line. But I’m not 100% sure if this could affect banking behavior or if it just depends on the name of sdld(gb).

**Comment by SuperDisk** [comment]
I think with the updated `rgb2sdas` this shouldn't be an issue now. Please let me know and reopen if that's not the case.
