### ISSUE TITLE
Error with add_VBL in  gbdk_player_example.c 

### ISSUE THREAD

**Issue by odrevet** [SuperDisk/hUGEDriver#33]
With GDBK 4.1.0 there is an error with `add_VBL(hUGE_dosound);`

```
gbdk_player_example.c:
gbdk_player_example.c:25: error 78: incompatible types
from type 'void function ( ) __sdcccall(0) fixed'
  to type 'void function ( ) code* fixed'
```

The example program builds and works when calling `hUGE_dosound();` in loop, before `wait_vbl_done();`, although this is less cool

**Comment by SuperDisk** [comment]
The calling conventions have been updated in #35 so this shouldn't be an issue now-- please let me know if that's not the case.
