### ISSUE TITLE
SGB Support?

### ISSUE THREAD

**Issue by nikku4211** [SuperDisk/hUGEDriver#39]
Would it be too difficult to add in support for SGB-enhanced music like in Hercules and Animaniacs into HUGEDriver?

It's never been done before in homebrew, so maybe it is very difficult.

**Comment by SuperDisk** [comment]
It's an interesting idea but it would involve writing some sort of Kankichi interface and integrating a SNES emulator, which is out of the scope of the project. I think you could sync up Kankichi with hUGE fairly easily though and just play both at the same time. You could use EBMused or AddMusicK or whatever for that.
